@echo off
REM ===========================================================================
REM  archive_legacy.bat — move superseded files into _old\
REM
REM  Everything moved here has already had its unique content extracted:
REM    * server.js  PLAN_EXTRA_SLIDERS      -> care_plans.json (extraSliders)
REM    * care_audit_report.html age bands,
REM      member options, unmapped field ids -> care_plans.json
REM    * unified.html printQuotes()         -> insurance_hub.html (Print / PDF)
REM    * quote_generator.html format spec   -> docs_reference_quotation_format.md
REM    * care_plan_audit_report.html
REM      open questions                     -> docs_reference_quotation_format.md
REM
REM  Nothing is deleted. Review _old\ and remove it yourself when you are ready.
REM  Run this from inside the Fresh_Approch folder.
REM ===========================================================================

cd /d "%~dp0"

if not exist "_old" mkdir "_old"

echo.
echo  Moving superseded files into _old\ ...
echo.

REM --- Fully superseded: nothing unique left in these -----------------------
call :move index.html                 "v1 Care UI - replaced by care_index.html, has no hub bridge"
call :move care_field_checker.html    "STALE - its SI_MAP is wrong by 10-50x on the Secure/Child plans"
call :move mc_index.html              "orphaned - every hub embeds mc_multi.html at /multi"
call :move hub_v2.html                "superseded by insurance_hub.html"
call :move node                       "stray 0-byte file"

REM --- Superseded, content extracted ---------------------------------------
call :move unified.html               "superseded - its print view now lives in insurance_hub.html"
call :move care_plan_audit_report.html "hand-written - open questions moved to docs_reference_quotation_format.md"

echo.
echo  ---------------------------------------------------------------
echo   KEPT ON PURPOSE (do not archive yet):
echo.
echo    server.js             package.json still references it, and it is
echo                          the only cheerio-based reference implementation
echo    quote_generator.html  the only way to hand-enter a competitor premium
echo                          (HDFC Ergo) or fill 2yr/3yr columns manually
echo    care_audit_report.html  regenerated by care_audit.js - keep the latest
echo    analyze_excel.py      needed if Vivek Bhaia_Quote.xlsx is ever found
echo    mc_probe*.js          the only documentation of the ManipalCigna API
echo    mc_bundle_scan.js     contract - keep as a research archive
echo    mc_test_covertype.js
echo    mc_api_test.html
echo  ---------------------------------------------------------------
echo.
echo  Done. Review _old\ before deleting anything.
echo.
pause
exit /b

:move
if not exist "%~1" (
  echo   [ -- ] %~1 - already moved or not present
  exit /b
)
move /Y "%~1" "_old\" >nul 2>&1
if errorlevel 1 (
  echo   [SKIP] %~1 - could not move, is it open in an editor?
) else (
  echo   [MOVED] %~1
  echo          %~2
)
exit /b
