#!/usr/bin/env python3
"""
verify_excel_format.py — regression test for the quotation spreadsheet format.

Compares a workbook generated by insurance_hub.html against the client
reference file `Vivek Bhaia_Quote.xlsx`, and asserts that every remaining
difference falls into one of the known, deliberate categories below. Anything
unclassified is a format regression and makes the script exit 1.

    python verify_excel_format.py <generated.xlsx> [--verbose]

The generated workbook must contain a sheet named "Four Member Quote" built
from the same data as the reference — see docs_excel_format_gap.md for the
fixture. The four sheets checked are the family sheet and Feature Comparison;
the group and single-member sheets are checked structurally only, since the
reference quotes different premiums on them.

Categories of accepted difference
---------------------------------
branding        Company names are normalised ("Care" -> "Care Health",
                "Niva Bupa " -> "Niva Bupa"). The reference was typed by hand
                and spells the same insurer three different ways.
date-drift      Ages are computed from the date of birth, so they advance.
source-typo     Trailing spaces and stray space characters in the reference.
blank-cell      The reference carries font / fill / alignment / number format
                on empty cells, left over from selecting whole ranges. Never
                visible; reproduced only where it is regular.
border-gap      The reference is missing internal borders on some cells
                (D27, E27, F27, row 49, row 56 …). Ours are complete.
addon-align     The reference's add-on and premium cells are inconsistently
                vertically aligned and carry stray number formats. Ours are
                uniformly middle-aligned and wrapped.
autofit-height  The reference stores Excel's cached auto-fit row heights for
                wrapped rows. We leave those rows without an explicit height so
                Excel recomputes them on open — which is how the reference's
                own numbers were produced.
default-width   H and P are an explicit 9 in the reference; ours inherit
                defaultColWidth=9. Identical on screen. (ExcelJS omits any
                width equal to the sheet default in any case.)
"""
import sys, openpyxl
from openpyxl.utils import get_column_letter as L

REF_PATH = 'Vivek Bhaia_Quote.xlsx'
SHEET    = 'Four Member Quote'

# Row bands of the reference family sheet, so a diff can be attributed.
INSURER_ROWS = set(range(27, 31)) | set(range(34, 38)) | set(range(41, 45)) \
             | set(range(48, 52)) | set(range(55, 59))
BLOCK_TITLES = {25, 32, 39, 46, 53}
BLOCK_HDRS   = {26, 33, 40, 47, 54}
CO_COLS      = {1, 9}            # Company
PREM_COLS    = {3, 4, 5, 6, 11, 12, 13, 14}
ADDON_COLS   = {7, 15}


def fill_of(c):
    f = c.fill
    if f is None or f.patternType is None:
        return None
    fg = f.fgColor
    if fg.type == 'rgb':   return ('rgb', fg.rgb)
    if fg.type == 'theme': return ('theme', fg.theme, round(fg.tint or 0, 3))
    return ('indexed', fg.indexed)


def style_of(c):
    return {
        'v':      c.value,
        'font':   (c.font.name, c.font.sz, bool(c.font.b), bool(c.font.u)),
        'fill':   fill_of(c),
        'align':  (c.alignment.horizontal, c.alignment.vertical, bool(c.alignment.wrap_text)),
        'numfmt': c.number_format,
        'border': tuple(getattr(c.border, s).style for s in ('left', 'right', 'top', 'bottom')),
    }


def classify(r, c, key, refv, outv, ref_ws, out_ws):
    """Return a category name, or None if the difference is unexplained."""
    # A cell holding only whitespace counts as empty: the reference has a stray
    # space in E24 of every quotation sheet, left over from clearing a cell.
    def blank(v):
        return v is None or (isinstance(v, str) and not v.strip())
    ref_empty = blank(ref_ws.cell(r, c).value)
    out_empty = blank(out_ws.cell(r, c).value)

    if key == 'v':
        if r in INSURER_ROWS and c in CO_COLS:
            return 'branding'
        if r in (14, 15, 16, 17) and c == 4:
            return 'date-drift'
        if isinstance(refv, str) and isinstance(outv, str) \
           and refv.strip() == outv.strip():
            return 'source-typo'
        if refv is not None and outv is None and str(refv).strip() == '':
            return 'source-typo'                 # E24 holds a single space
        if (refv is None) != (outv is None) and r == 21:
            return 'source-typo'                 # unfilled existing-policy field
        return None

    if ref_empty and out_empty:
        return 'blank-cell'

    if key == 'border':
        # Accepted only where the reference is the one missing an edge.
        if any(a is None and b is not None for a, b in zip(refv, outv)):
            return 'border-gap'
        return None

    if key in ('align', 'numfmt') and (c in ADDON_COLS or c in PREM_COLS) \
       and r in INSURER_ROWS:
        return 'addon-align'

    if key == 'numfmt' and r == 21:
        return 'blank-cell'

    return None


def compare(ref, out, verbose=False):
    rs, os_ = ref[SHEET], out[SHEET]
    problems, counts = [], {}

    print(f'sheet "{SHEET}"')
    print(f'  dimensions       ref {rs.max_row}x{rs.max_column}   '
          f'out {os_.max_row}x{os_.max_column}'
          f'   {"OK" if (rs.max_row, rs.max_column) == (os_.max_row, os_.max_column) else "MISMATCH"}')
    if (rs.max_row, rs.max_column) != (os_.max_row, os_.max_column):
        problems.append('sheet dimensions differ')

    rm = sorted(str(m) for m in rs.merged_cells.ranges)
    om = sorted(str(m) for m in os_.merged_cells.ranges)
    print(f'  merged ranges    {len(rm)}   {"IDENTICAL" if rm == om else "MISMATCH"}')
    if rm != om:
        problems.append(f'merges differ: only in ref {[m for m in rm if m not in om]}, '
                        f'only in out {[m for m in om if m not in rm]}')

    def widths(ws):
        return {k: round(v.width, 1) for k, v in ws.column_dimensions.items() if v.width}
    rw, ow = widths(rs), widths(os_)
    bad = [k for k in set(rw) | set(ow) if rw.get(k) != ow.get(k)]
    unexplained = [k for k in bad if not (k in ('H', 'P') and rw.get(k) == 9.0
                                          and ow.get(k) is None)]
    print(f'  column widths    {len(rw)} explicit   '
          f'{"IDENTICAL" if not bad else "default-width on " + ",".join(sorted(bad))}'
          f'{"" if not unexplained else "  UNEXPLAINED: " + ",".join(sorted(unexplained))}')
    if unexplained:
        problems.append(f'column widths differ: {unexplained}')
    if bad:
        counts['default-width'] = counts.get('default-width', 0) + len(bad)

    print(f'  defaultColWidth  ref {rs.sheet_format.defaultColWidth}   '
          f'out {os_.sheet_format.defaultColWidth}')

    # Row heights: 18.75 must match exactly; anything taller in the reference is
    # Excel's cached auto-fit on a wrapped row and must be absent in ours.
    def heights(ws):
        return {k: round(v.height, 2) for k, v in ws.row_dimensions.items() if v.height}
    rh, oh = heights(rs), heights(os_)
    hbad = []
    for k in sorted(set(rh) | set(oh)):
        a, b = rh.get(k), oh.get(k)
        if a == b:
            continue
        if a is not None and b is None and a != 18.75:
            counts['autofit-height'] = counts.get('autofit-height', 0) + 1
        elif a is not None and b is None and a == 18.75 and k in INSURER_ROWS:
            counts['autofit-height'] = counts.get('autofit-height', 0) + 1
        elif a is None and b == 18.75:
            # Row 52 is the one row in the reference's used range with no height
            # at all — an oversight in the original. Ours is uniform.
            counts['blank-cell'] = counts.get('blank-cell', 0) + 1
        else:
            hbad.append((k, a, b))
    print(f'  row heights      {len(rh)} explicit   '
          f'{"OK" if not hbad else "UNEXPLAINED: " + str(hbad)}')
    if hbad:
        problems.append(f'row heights differ: {hbad}')

    for r in range(1, max(rs.max_row, os_.max_row) + 1):
        for c in range(1, max(rs.max_column, os_.max_column) + 1):
            a, b = style_of(rs.cell(r, c)), style_of(os_.cell(r, c))
            for key in a:
                if a[key] == b[key]:
                    continue
                cat = classify(r, c, key, a[key], b[key], rs, os_)
                if cat is None:
                    problems.append(f'{L(c)}{r} {key}: ref {a[key]!r} != out {b[key]!r}')
                else:
                    counts[cat] = counts.get(cat, 0) + 1
                    if verbose:
                        print(f'      [{cat}] {L(c)}{r} {key}: {a[key]!r} -> {b[key]!r}')

    print('\n  accepted differences by category')
    for k in sorted(counts):
        print(f'    {k:<16} {counts[k]}')
    return problems


def compare_features(ref, out):
    if 'Feature Comparison' not in out.sheetnames:
        return ['Feature Comparison sheet missing from the generated workbook']
    rs, os_ = ref['Feature Comparison'], out['Feature Comparison']
    problems = []
    print('\nsheet "Feature Comparison"')

    # Two deliberate departures from the reference, both requested:
    #
    #  1. The sheet is now LAST in the workbook. The reference put it second,
    #     right after the family sheet, which buried the per-member premiums
    #     behind a page of product terms.
    #  2. When a column describes a plan other than the one quoted — or an
    #     insurer whose features have never been captured — a "Please note" row
    #     is inserted under the header saying so. That shifts every row below it
    #     down by one, so the reference is compared against the output offset by
    #     the note row rather than being declared mismatched wholesale.
    if out.sheetnames[-1] != 'Feature Comparison':
        problems.append('Feature Comparison should be the last sheet, found at position '
                        f'{out.sheetnames.index("Feature Comparison") + 1} of {len(out.sheetnames)}')
    note = 2 if str(os_.cell(2, 1).value or '').startswith('Please note') else 0
    print(f'  {"position":<16} {"LAST" if out.sheetnames[-1] == "Feature Comparison" else "NOT LAST"}')
    print(f'  {"note row":<16} {"present (rows below shift by 1)" if note else "absent"}')

    def shift_ranges(ranges, by):
        """Move every merge below the note row down by `by` rows."""
        moved = []
        for m in ranges:
            r1, r2 = m.min_row, m.max_row
            if r1 >= 2:
                r1, r2 = r1 + by, r2 + by
            moved.append(f'{L(m.min_col)}{r1}:'
                         f'{L(m.max_col)}{r2}')
        return sorted(moved)

    ref_merges = (shift_ranges(rs.merged_cells.ranges, 1) if note
                  else sorted(str(m) for m in rs.merged_cells.ranges))
    ref_heights = ({(int(k) + 1 if int(k) >= 2 else int(k)): round(v.height, 1)
                    for k, v in rs.row_dimensions.items() if v.height} if note
                   else {int(k): round(v.height, 1) for k, v in rs.row_dimensions.items() if v.height})
    out_heights = {int(k): round(v.height, 1) for k, v in os_.row_dimensions.items() if v.height}
    if note:
        # The note row's own height is new, so it is not in the reference.
        out_heights.pop(note, None)

    for label, a, b in (
        ('dimensions', (rs.max_row + (1 if note else 0), rs.max_column),
                       (os_.max_row, os_.max_column)),
        ('merges', ref_merges,
                   sorted(str(m) for m in os_.merged_cells.ranges
                          if not (note and m.min_row == note))),
        ('widths', {k: round(v.width, 1) for k, v in rs.column_dimensions.items()
                    if v.width and k != 'H'},
                   {k: round(v.width, 1) for k, v in os_.column_dimensions.items() if v.width}),
        ('heights', ref_heights, out_heights),
    ):
        ok = a == b
        print(f'  {label:<16} {"IDENTICAL" if ok else "MISMATCH"}')
        if not ok:
            problems.append(f'Feature Comparison {label}: ref {a} != out {b}')
    # Fills are compared by COLUMN LABEL, not position. The plan columns are now
    # chosen from the quotation, so a column can legitimately be absent — HDFC
    # Ergo is in the reference but no hub calculator can quote it, so it is
    # dropped and everything to its right shifts left. Comparing column 7 to
    # column 7 would then flag a difference that is the whole point of the
    # change. Matching on the header text checks the columns that do survive and
    # says plainly which ones did not.
    def headers(ws, hdr_row):
        return {str(ws.cell(hdr_row, c).value): c
                for c in range(3, ws.max_column + 1) if ws.cell(hdr_row, c).value}
    ref_hdr, out_hdr = headers(rs, 1), headers(os_, 1)
    dropped = [h for h in ref_hdr if h not in out_hdr]
    added   = [h for h in out_hdr if h not in ref_hdr]
    print(f'  {"columns":<16} {len(out_hdr)} of the reference\'s {len(ref_hdr)}'
          + (f'  dropped {[h.split(chr(10))[0][:22] for h in dropped]}' if dropped else '')
          + (f'  added {[h[:22] for h in added]}' if added else ''))

    fills = []
    for r in range(1, rs.max_row + 1):
        ro = r + (1 if note and r >= 2 else 0)
        for c in (1, 2):                              # the two label columns
            if fill_of(rs.cell(r, c)) != fill_of(os_.cell(ro, c)):
                fills.append((r, c))
        for h, rc in ref_hdr.items():                 # each surviving plan column
            oc = out_hdr.get(h)
            if oc is None:
                continue
            if fill_of(rs.cell(r, rc)) != fill_of(os_.cell(ro, oc)):
                fills.append((r, h.split('\n')[0][:18]))
    print(f'  {"fills":<16} {"IDENTICAL" if not fills else "MISMATCH " + str(fills[:8])}')
    if fills:
        problems.append(f'Feature Comparison fills differ at {fills[:8]}')

    # And the values in every surviving column must be unchanged. This is the
    # assertion that catches the real hazard of dropping a column: each feature
    # row's values are positional against the original five, so a writer that
    # renumbered them would attribute one insurer's terms to another.
    vals = []
    for r in range(2, rs.max_row + 1):
        ro = r + (1 if note else 0)
        for h, rc in ref_hdr.items():
            oc = out_hdr.get(h)
            if oc is None:
                continue
            # Whitespace is normalised: the reference has stray leading and
            # trailing spaces (the source-typo category) and hard line breaks
            # inside cells that ExcelJS writes as spaces. Neither says anything
            # about whether a value landed in the right column, which is what
            # this check is for.
            def norm(v):
                return ' '.join(str(v or '').split())
            a, b = rs.cell(r, rc).value, os_.cell(ro, oc).value
            if norm(a) != norm(b):
                vals.append((r, h.split('\n')[0][:18], a, b))
    print(f'  {"column values":<16} {"IDENTICAL" if not vals else "MISMATCH " + str(vals[:4])}')
    if vals:
        problems.append(f'Feature Comparison values moved between columns: {vals[:4]}')

    # Fonts, which this check used to skip entirely — and that is how the sheet
    # sat at 14pt against the reference's 11pt without anything noticing.
    def fonts(ws):
        out = set()
        for r in range(1, ws.max_row + 1):
            for c in range(1, 8):
                cell = ws.cell(r, c)
                if cell.value not in (None, ''):
                    out.add((cell.font.name, cell.font.sz))
        return out
    rf, of = fonts(rs), fonts(os_)
    ok = rf == of
    print(f'  {"fonts":<16} {"IDENTICAL " + str(sorted(rf)) if ok else "MISMATCH ref " + str(sorted(rf)) + " out " + str(sorted(of))}')
    if not ok:
        problems.append(f'Feature Comparison fonts: ref {sorted(rf)} != out {sorted(of)}')
    return problems


def check_landmarks(out):
    """The block-title row is the load-bearing landmark of each sheet shape."""
    problems = []
    print('\nsheet shapes (first block title row)')
    expect = {'Four Member Quote': (25, 15), 'Vivek & Pratibha Bhaia Quote': (23, 15)}
    for nm in out.sheetnames:
        if nm == 'Feature Comparison':
            continue
        ws = out[nm]
        title = next((r for r in range(7, 40)
                      if isinstance(ws.cell(r, 1).value, str)
                      and 'Quotation For' in ws.cell(r, 1).value), None)
        want = expect.get(nm, (22, 7))
        ok = title == want[0] and ws.max_column == want[1]
        print(f'  {nm:<30} title row {title} (want {want[0]}), '
              f'{ws.max_column} columns (want {want[1]})  {"OK" if ok else "MISMATCH"}')
        if not ok:
            problems.append(f'{nm}: title row {title} / {ws.max_column} cols, want {want}')
    return problems


def main():
    args = [a for a in sys.argv[1:] if not a.startswith('--')]
    verbose = '--verbose' in sys.argv
    if not args:
        print(__doc__)
        return 2
    ref = openpyxl.load_workbook(REF_PATH)
    out = openpyxl.load_workbook(args[0])
    problems = compare(ref, out, verbose)
    problems += compare_features(ref, out)
    problems += check_landmarks(out)
    print()
    if problems:
        print(f'FAIL — {len(problems)} unexplained difference(s):')
        for p in problems[:40]:
            print('  ' + p)
        if len(problems) > 40:
            print(f'  … and {len(problems) - 40} more')
        return 1
    print('PASS — every difference from the reference is a known, deliberate one.')
    return 0


if __name__ == '__main__':
    sys.exit(main())
